basePath: /pf-admin-api/v1
definitions:
  ApiResult:
    description: Details on the result of the operation.
    properties:
      developerMessage:
        description: 'Developer-oriented error message, if available.'
        type: string
      message:
        description: Success or error message.
        type: string
      resultId:
        description: Result identifier.
        type: string
      validationErrors:
        description: 'List of validation errors, if any.'
        items:
          $ref: '#/definitions/ValidationError'
        type: array
  AuthenticationPolicyContract:
    description: >-
      Authentication Policy Contracts carry user attributes from the identity
      provider to the service provider.
    properties:
      coreAttributes:
        description: >-
          A list of read-only assertion attributes (for example, subject) that
          are automatically populated by PingFederate.
        items:
          $ref: '#/definitions/AuthenticationPolicyContractAttribute'
        type: array
      extendedAttributes:
        description: A list of additional attributes as needed.
        items:
          $ref: '#/definitions/AuthenticationPolicyContractAttribute'
        type: array
      id:
        description: >-
          The persistent, unique ID for the authentication policy contract. It
          can be any combination of [a-zA-Z0-9._-]. This property is
          system-assigned if not specified.
        type: string
      name:
        description: The Authentication Policy Contract Name. Name is unique.
        type: string
  AuthenticationPolicyContractAttribute:
    description: An attribute for the Authentication Policy Contract.
    properties:
      name:
        description: The name of this attribute.
        type: string
    required:
      - name
  AuthenticationPolicyContracts:
    description: A collection of Authentication Policy Contracts
    properties:
      items:
        description: The actual list of Authentication Policy Contracts.
        items:
          $ref: '#/definitions/AuthenticationPolicyContract'
        type: array
  ValidationError:
    description: A data input validation error.
    properties:
      developerMessage:
        description: 'Developer-oriented error message, if available.'
        type: string
      errorId:
        description: Error identifier.
        type: string
      fieldPath:
        description: 'The path to the model field to which the error relates, if one exists.'
        type: string
      message:
        description: User-friendly error description.
        type: string
host: 'ip-10-101-29-72:9999'
info:
  title: 'ip-10-101-29-72:9999'
  version: v1
paths:
  /authenticationPolicyContracts:
    get:
      operationId: getAuthenticationPolicyContracts
      parameters:
        - description: Page number to retrieve.
          format: int32
          in: query
          name: page
          required: false
          type: integer
        - description: Number of contracts per page.
          format: int32
          in: query
          name: numberPerPage
          required: false
          type: integer
        - description: >-
            Filter criteria limits the authentication policy contracts that are
            returned to only those that match it. The filter criteria is
            compared to the authentication policy contract name and ID fields.
            The comparison is a case-insensitive partial match. No additional
            pattern based matching is supported.
          in: query
          name: filter
          required: false
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Success.
          schema:
            $ref: '#/definitions/AuthenticationPolicyContracts'
        '403':
          description: >-
            PingFederate does not have the appropriate IdP/SP role enabled.
            Operation not available.
        '422':
          description: Validation error(s) occurred.
          schema:
            $ref: '#/definitions/ApiResult'
      summary: Gets the Authentication Policy Contracts.
    post:
      consumes:
        - application/json
      description: >-
        Create a new Authentication Policy Contract. If the Authentication
        Policy Contract is not properly configured, a 422 status code is
        returned along with a list of validation errors that must be corrected.
      operationId: createAuthenticationPolicyContract
      parameters:
        - description: Configuration for a new contract.
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/AuthenticationPolicyContract'
      produces:
        - application/json
      responses:
        '200':
          description: No response was specified
          schema:
            $ref: '#/definitions/AuthenticationPolicyContract'
        '201':
          description: Authentication policy contract created.
        '400':
          description: The request was improperly formatted or contained invalid fields.
        '403':
          description: >-
            PingFederate does not have the appropriate IdP/SP role enabled.
            Operation not available.
        '422':
          description: Validation error(s) occurred.
          schema:
            $ref: '#/definitions/ApiResult'
      summary: Create a new Authentication Policy Contract.
  '/authenticationPolicyContracts/{id}':
    delete:
      description: >-
        Delete an Authentication Policy Contract with the specified ID. A 404
        status code is returned for nonexistent IDs. Note: If the request
        succeeds, the response body is empty. If the request fails, an ApiResult
        is returned with details of the error.
      operationId: deleteAuthenticationPolicyContract
      parameters:
        - description: ID of Authentication Policy Contract to delete.
          in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: No response was specified
          schema:
            $ref: '#/definitions/ApiResult'
        '204':
          description: Authentication policy contract deleted.
        '403':
          description: >-
            PingFederate does not have the appropriate IdP/SP role enabled.
            Operation not available.
        '404':
          description: Resource not found.
        '422':
          description: Resource is in use and cannot be deleted.
          schema:
            $ref: '#/definitions/ApiResult'
      summary: Delete an Authentication Policy Contract.
    get:
      description: >-
        Get an Authentication Policy Contract with the specified ID. A 404
        status code is returned for nonexistent IDs
      operationId: getAuthenticationPolicyContract
      parameters:
        - description: ID of contract to fetch
          in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Success.
          schema:
            $ref: '#/definitions/AuthenticationPolicyContract'
        '403':
          description: >-
            PingFederate does not have the appropriate IdP/SP role enabled.
            Operation not available.
        '404':
          description: Resource not found.
          schema:
            $ref: '#/definitions/ApiResult'
      summary: Gets the Authentication Policy Contract by ID.
    put:
      description: >-
        Update an Authentication Policy Contract with the specified ID. A 404
        status code is returned for nonexistent IDs.
      operationId: updateAuthenticationPolicyContract
      parameters:
        - description: ID of the Authentication Policy Contract to update.
          in: path
          name: id
          required: true
          type: string
        - description: Configuration for updated Authentication Policy Contract.
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/AuthenticationPolicyContract'
      produces:
        - application/json
      responses:
        '200':
          description: Authentication policy contract updated.
          schema:
            $ref: '#/definitions/AuthenticationPolicyContract'
        '400':
          description: The request was improperly formatted or contained invalid fields.
        '403':
          description: >-
            PingFederate does not have the appropriate IdP/SP role enabled.
            Operation not available.
        '404':
          description: Resource not found.
          schema:
            $ref: '#/definitions/ApiResult'
        '422':
          description: Validation error(s) occurred.
          schema:
            $ref: '#/definitions/ApiResult'
      summary: Update an Authentication Policy Contract by ID.
schemes:
  - https
swagger: '2.0'

