basePath: /pf-admin-api/v1
definitions:
  ApiResult:
    description: Details on the result of the operation.
    properties:
      developerMessage:
        description: 'Developer-oriented error message, if available.'
        type: string
      message:
        description: Success or error message.
        type: string
      resultId:
        description: Result identifier.
        type: string
      validationErrors:
        description: 'List of validation errors, if any.'
        items:
          $ref: '#/definitions/ValidationError'
        type: array
  CertView:
    description: Certificate details.
    properties:
      cryptoProvider:
        $ref: '#/definitions/CryptoProvider'
        description: >-
          Cryptographic Provider. This is only applicable if Hybrid HSM mode is
          true.
        enum:
          - LOCAL
          - HSM
      expires:
        description: >-
          The end date up until which the item is valid, in ISO 8601 format
          (UTC).
        format: date-time
        type: string
      id:
        description: 'The persistent, unique ID for the certificate.'
        type: string
      issuerDN:
        description: The issuer's distinguished name.
        type: string
      keyAlgorithm:
        description: The public key algorithm.
        type: string
      keySize:
        description: The public key size.
        format: int32
        type: integer
      serialNumber:
        description: The serial number assigned by the CA.
        type: string
      sha1Fingerprint:
        description: SHA-1 fingerprint in Hex encoding.
        type: string
      sha256Fingerprint:
        description: SHA-256 fingerprint in Hex encoding.
        type: string
      signatureAlgorithm:
        description: The signature algorithm.
        type: string
      status:
        $ref: '#/definitions/CertificateValidity'
        description: Status of the item.
        enum:
          - VALID
          - EXPIRED
          - NOT_YET_VALID
          - REVOKED
      subjectAlternativeNames:
        description: The subject alternative names (SAN).
        items:
          type: string
        type: array
      subjectDN:
        description: The subject's distinguished name.
        type: string
      validFrom:
        description: 'The start date from which the item is valid, in ISO 8601 format (UTC).'
        format: date-time
        type: string
      version:
        description: The X.509 version to which the item conforms.
        format: int32
        type: integer
  CertViews:
    description: A collection of Certificate items.
    properties:
      items:
        description: The actual list of certificate instances.
        items:
          $ref: '#/definitions/CertView'
        type: array
  ValidationError:
    description: A data input validation error.
    properties:
      developerMessage:
        description: 'Developer-oriented error message, if available.'
        type: string
      errorId:
        description: Error identifier.
        type: string
      fieldPath:
        description: 'The path to the model field to which the error relates, if one exists.'
        type: string
      message:
        description: User-friendly error description.
        type: string
  X509File:
    description: Encoded certificate data.
    properties:
      cryptoProvider:
        $ref: '#/definitions/CryptoProvider'
        description: >-
          Cryptographic Provider. This is only applicable if Hybrid HSM mode is
          true.
        enum:
          - LOCAL
          - HSM
      fileData:
        description: >-
          The certificate data in PEM format. New line characters should be
          omitted or encoded in this value.
        type: string
      id:
        description: >-
          The persistent, unique ID for the certificate. It can be any
          combination of [a-z0-9._-]. This property is system-assigned if not
          specified.
        type: string
    required:
      - fileData
host: 'ip-10-101-29-72:9999'
info:
  title: 'ip-10-101-29-72:9999'
  version: v1
paths:
  /certificates/ca:
    get:
      operationId: getTrustedCAs
      produces:
        - application/json
      responses:
        '200':
          description: Success.
          schema:
            $ref: '#/definitions/CertViews'
      summary: Get list of trusted certificate authorities.
  /certificates/ca/import:
    post:
      consumes:
        - application/json
      operationId: importTrustedCA
      parameters:
        - description: File data to import.
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/X509File'
      produces:
        - application/json
      responses:
        '200':
          description: No response was specified
          schema:
            $ref: '#/definitions/CertView'
        '201':
          description: Certificate Authority imported.
        '400':
          description: The request was improperly formatted or contained invalid fields.
        '422':
          description: Validation error(s) occurred.
      summary: Import a new trusted certificate authority.
  '/certificates/ca/{id}':
    delete:
      description: >-
        If the request is successful, the response body is empty. If the request
        fails, an ApiResult is returned with details of the error.
      operationId: deleteTrustedCA
      parameters:
        - description: ID of the trusted certificate authority to delete.
          in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: No response was specified
          schema:
            $ref: '#/definitions/ApiResult'
        '204':
          description: Certitifcate Authority deleted.
        '404':
          description: Resource not found.
      summary: Delete a trusted certificate authority.
    get:
      operationId: getTrustedCert
      parameters:
        - description: ID of the trusted certificate authority to retrieve.
          in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Success.
          schema:
            $ref: '#/definitions/CertView'
        '404':
          description: Resource not found.
      summary: Retrieve details of a trusted certificate authority.
  '/certificates/ca/{id}/file':
    get:
      description: >-
        For a successful request, the PEM-encoded certificate file is directly
        returned as text and the response content type is
        application/x-x509-ca-cert. If an error occurs, an ApiResult is returned
        in JSON format and the content type is application/json.
      operationId: exportCertificateFile
      parameters:
        - description: ID of the trusted certificate authority.
          in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Success.
          schema:
            type: string
        '404':
          description: Resource not found.
      summary: Download the certificate from a given trusted certificate authority.
schemes:
  - https
swagger: '2.0'

