basePath: /pf-admin-api/v1
definitions:
  ApiResult:
    description: Details on the result of the operation.
    properties:
      developerMessage:
        description: 'Developer-oriented error message, if available.'
        type: string
      message:
        description: Success or error message.
        type: string
      resultId:
        description: Result identifier.
        type: string
      validationErrors:
        description: 'List of validation errors, if any.'
        items:
          $ref: '#/definitions/ValidationError'
        type: array
  CertView:
    description: Certificate details.
    properties:
      cryptoProvider:
        $ref: '#/definitions/CryptoProvider'
        description: >-
          Cryptographic Provider. This is only applicable if Hybrid HSM mode is
          true.
        enum:
          - LOCAL
          - HSM
      expires:
        description: >-
          The end date up until which the item is valid, in ISO 8601 format
          (UTC).
        format: date-time
        type: string
      id:
        description: 'The persistent, unique ID for the certificate.'
        type: string
      issuerDN:
        description: The issuer's distinguished name.
        type: string
      keyAlgorithm:
        description: The public key algorithm.
        type: string
      keySize:
        description: The public key size.
        format: int32
        type: integer
      serialNumber:
        description: The serial number assigned by the CA.
        type: string
      sha1Fingerprint:
        description: SHA-1 fingerprint in Hex encoding.
        type: string
      sha256Fingerprint:
        description: SHA-256 fingerprint in Hex encoding.
        type: string
      signatureAlgorithm:
        description: The signature algorithm.
        type: string
      status:
        $ref: '#/definitions/CertificateValidity'
        description: Status of the item.
        enum:
          - VALID
          - EXPIRED
          - NOT_YET_VALID
          - REVOKED
      subjectAlternativeNames:
        description: The subject alternative names (SAN).
        items:
          type: string
        type: array
      subjectDN:
        description: The subject's distinguished name.
        type: string
      validFrom:
        description: 'The start date from which the item is valid, in ISO 8601 format (UTC).'
        format: date-time
        type: string
      version:
        description: The X.509 version to which the item conforms.
        format: int32
        type: integer
  CertViews:
    description: A collection of Certificate items.
    properties:
      items:
        description: The actual list of certificate instances.
        items:
          $ref: '#/definitions/CertView'
        type: array
  CertificateRevocationSettings:
    description: Certificate revocation settings.
    properties:
      crlSettings:
        $ref: '#/definitions/CrlSettings'
        description: >-
          Certificate revocation CRL settings. CRL revocation is enabled by
          default. It will be disabled if this attribute is not defined in the
          request body.
      ocspSettings:
        $ref: '#/definitions/OcspSettings'
        description: >-
          Certificate revocation OCSP settings. OCSP revocation is disabled by
          default. It will be enabled if this attribute is defined in the
          request body.
      proxySettings:
        $ref: '#/definitions/ProxySettings'
        description: >-
          If OCSP messaging is routed through a proxy server, specify the
          server's host (DNS name or IP address) and the port number. The same
          proxy information applies to CRL checking, when CRL is enabled for
          failover.
  CrlSettings:
    description: CRL settings.
    properties:
      nextRetryMinsWhenNextUpdateInPast:
        description: >-
          Next retry on next update expiration in minutes. This value defaults
          to "60".
        format: int32
        type: integer
      nextRetryMinsWhenResolveFailed:
        description: >-
          Next retry on resolution failure in minutes. This value defaults to
          "1440".
        format: int32
        type: integer
      treatNonRetrievableCrlAsRevoked:
        description: >-
          Treat non retrievable CRL as revoked. This setting defaults to
          disabled.
        type: boolean
      verifyCrlSignature:
        description: Verify CRL signature. This setting defaults to enabled.
        type: boolean
  OcspSettings:
    description: OCSP settings.
    properties:
      actionOnResponderUnavailable:
        description: Action on responder unavailable. This value defaults to  "CONTINUE".
        type: string
      actionOnStatusUnknown:
        description: Action on status unknown. This value defaults to  "FAIL".
        type: string
      actionOnUnsuccessfulResponse:
        description: Action on unsuccessful response. This value defaults to  "FAIL".
        type: string
      currentUpdateGracePeriod:
        description: Current update grace period in minutes. This value defaults to "5".
        format: int32
        type: integer
      nextUpdateGracePeriod:
        description: Next update grace period in minutes. This value defaults to "5".
        format: int32
        type: integer
      requesterAddNonce:
        description: >-
          Do not allow responder to use cached responses. This setting defaults
          to disabled.
        type: boolean
      responderCertReference:
        $ref: '#/definitions/ResourceLink'
        description: >-
          Resource link to OCSP responder signature verification certificate. A
          previously selected certificate will be deselected if this attribute
          is not defined.
      responderTimeout:
        description: Responder connection timeout in seconds. This value defaults to "5".
        format: int32
        type: integer
      responderUrl:
        description: >-
          Responder URL address. This field is required if OCSP revocation is
          enabled.
        type: string
      responseCachePeriod:
        description: Response cache period in hours. This value defaults to "48".
        format: int32
        type: integer
    required:
      - responderUrl
  ProxySettings:
    description: Proxy settings.
    properties:
      host:
        description: Host name.
        type: string
      port:
        description: Port number.
        format: int32
        type: integer
  ResourceLink:
    description: A reference to a resource.
    properties:
      id:
        description: The ID of the resource.
        type: string
      location:
        description: >-
          A read-only URL that references the resource. If the resource is not
          currently URL-accessible, this property will be null.
        type: string
    required:
      - id
  ValidationError:
    description: A data input validation error.
    properties:
      developerMessage:
        description: 'Developer-oriented error message, if available.'
        type: string
      errorId:
        description: Error identifier.
        type: string
      fieldPath:
        description: 'The path to the model field to which the error relates, if one exists.'
        type: string
      message:
        description: User-friendly error description.
        type: string
  X509File:
    description: Encoded certificate data.
    properties:
      cryptoProvider:
        $ref: '#/definitions/CryptoProvider'
        description: >-
          Cryptographic Provider. This is only applicable if Hybrid HSM mode is
          true.
        enum:
          - LOCAL
          - HSM
      fileData:
        description: >-
          The certificate data in PEM format. New line characters should be
          omitted or encoded in this value.
        type: string
      id:
        description: >-
          The persistent, unique ID for the certificate. It can be any
          combination of [a-z0-9._-]. This property is system-assigned if not
          specified.
        type: string
    required:
      - fileData
host: 'ip-10-101-29-72:9999'
info:
  title: 'ip-10-101-29-72:9999'
  version: v1
paths:
  /certificates/revocation/ocspCertificates:
    get:
      operationId: getOcspCertificates
      produces:
        - application/json
      responses:
        '200':
          description: Success.
          schema:
            $ref: '#/definitions/CertViews'
      summary: >-
        Get the list of available OCSP responder signature verification
        certificates.
    post:
      consumes:
        - application/json
      operationId: importOcspCertificate
      parameters:
        - description: File to import.
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/X509File'
      produces:
        - application/json
      responses:
        '200':
          description: No response was specified
          schema:
            $ref: '#/definitions/CertView'
        '201':
          description: OCSP responder signature verification certificate imported.
        '400':
          description: The request was improperly formatted or contained invalid fields.
        '422':
          description: Validation error(s) occurred.
          schema:
            $ref: '#/definitions/ApiResult'
      summary: Import an OCSP responder signature verification certificate.
  '/certificates/revocation/ocspCertificates/{id}':
    delete:
      operationId: deleteOcspCertificateById
      parameters:
        - description: Certificate ID.
          in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: No response was specified
          schema:
            $ref: '#/definitions/ApiResult'
        '204':
          description: OCSP responder signature verification certificate deleted.
        '404':
          description: Resource not found.
        '422':
          description: Resource is in use and cannot be deleted.
      summary: Delete an OCSP responder signature verification certificate by ID.
    get:
      operationId: getOcspCertificateById
      parameters:
        - description: Certificate ID.
          in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Success.
          schema:
            $ref: '#/definitions/CertView'
        '404':
          description: Resource not found.
          schema:
            $ref: '#/definitions/ApiResult'
      summary: Get an OCSP responder signature verification certificate by ID.
  /certificates/revocation/settings:
    get:
      operationId: getRevocationSettings
      produces:
        - application/json
      responses:
        '200':
          description: Success.
          schema:
            $ref: '#/definitions/CertificateRevocationSettings'
      summary: Get certificate revocation settings.
    put:
      consumes:
        - application/json
      operationId: updateRevocationSettings
      parameters:
        - description: Certificate revocation settings.
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/CertificateRevocationSettings'
      produces:
        - application/json
      responses:
        '200':
          description: Certificate revocation settings updated.
          schema:
            $ref: '#/definitions/CertificateRevocationSettings'
        '400':
          description: The request was improperly formatted or contained invalid fields.
        '422':
          description: Validation error(s) occurred.
          schema:
            $ref: '#/definitions/ApiResult'
      summary: Update certificate revocation settings.
schemes:
  - https
swagger: '2.0'

