basePath: /pf-admin-api/v1
definitions:
  ApiResult:
    description: Details on the result of the operation.
    properties:
      developerMessage:
        description: 'Developer-oriented error message, if available.'
        type: string
      message:
        description: Success or error message.
        type: string
      resultId:
        description: Result identifier.
        type: string
      validationErrors:
        description: 'List of validation errors, if any.'
        items:
          $ref: '#/definitions/ValidationError'
        type: array
  ClusterNode:
    description: Describes a node in a clustered deployment of PingFederate.
    properties:
      address:
        description: The IP address and port this node is running on.
        type: string
      index:
        description: >-
          Index of the node within the cluster, or -1 if an index is not
          assigned.
        format: int32
        type: integer
      mode:
        $ref: '#/definitions/DeploymentMode'
        description: 'The deployment mode of this node, from a clustering standpoint.'
        enum:
          - CLUSTERED_ENGINE
          - CLUSTERED_CONSOLE
          - CLUSTERED_DUAL
          - STANDALONE
      nodeGroup:
        description: >-
          The node group for this node. This field is only populated if adaptive
          clustering is enabled.
        type: string
      nodeTags:
        description: >-
          The node tags for this node. This field is only populated for engine
          nodes.
        type: string
      version:
        description: The PingFederate version this node is running on.
        type: string
  ClusterStatus:
    description: Information on cluster nodes and replication status.
    properties:
      lastConfigUpdateTime:
        description: Time when the configuration of this node was last updated.
        format: date-time
        type: string
      lastReplicationTime:
        description: Time when configuration changes were last replicated.
        format: date-time
        type: string
      mixedMode:
        description: >-
          Indicates whether there is more than one version of PingFederate in
          the cluster.
        type: boolean
      nodes:
        description: List of nodes in the cluster.
        items:
          $ref: '#/definitions/ClusterNode'
        type: array
      replicationRequired:
        description: >-
          Indicates whether a replication is required to propagate config
          updates.
        type: boolean
  ValidationError:
    description: A data input validation error.
    properties:
      developerMessage:
        description: 'Developer-oriented error message, if available.'
        type: string
      errorId:
        description: Error identifier.
        type: string
      fieldPath:
        description: 'The path to the model field to which the error relates, if one exists.'
        type: string
      message:
        description: User-friendly error description.
        type: string
host: 'ip-10-101-29-72:9999'
info:
  title: 'ip-10-101-29-72:9999'
  version: v1
paths:
  /cluster/replicate:
    post:
      operationId: startReplication
      produces:
        - application/json
      responses:
        '200':
          description: Replication completed successfully.
          schema:
            $ref: '#/definitions/ApiResult'
        '403':
          description: This PingFederate instance is not deployed in clustered mode.
      summary: Replicate configuration updates to all nodes in the cluster.
  /cluster/status:
    get:
      operationId: getClusterStatus
      produces:
        - application/json
      responses:
        '200':
          description: Success.
          schema:
            $ref: '#/definitions/ClusterStatus'
        '403':
          description: This PingFederate instance is not deployed in clustered mode.
      summary: Get information on the current status of the cluster.
schemes:
  - https
swagger: '2.0'

