basePath: /pf-admin-api/v1
definitions:
  ActionDescriptor:
    description: Describes an arbitrary action that is available for a plugin.
    properties:
      description:
        description: The description of this action
        type: string
      download:
        description: >-
          Whether this action will trigger a download or invoke an internal
          action that will return a string result.
        type: boolean
      downloadContentType:
        description: >-
          If this is a download, this is the Content-Type of the downloaded
          file. Otherwise, this is null.
        type: string
      downloadFileName:
        description: >-
          If this is a download, this is the suggested file name of the
          downloaded file. Otherwise, this is null.
        type: string
      name:
        description: The name of this action
        type: string
  BaseSelectionFieldDescriptor:
    description: Holds fields that are shared by all selection-type field descriptors.
    properties:
      advanced:
        description: Whether this is an advanced field or not.
        type: boolean
      defaultValue:
        description: Default value of the field.
        type: string
      description:
        description: Description of the field.
        type: string
      label:
        description: Label of the field to be displayed in the administrative console.
        type: string
      name:
        description: Name of the field.
        type: string
      optionValues:
        description: The list of option values for this selection field.
        items:
          $ref: '#/definitions/OptionValue'
        type: array
      required:
        description: Whether a value is required for this field or not.
        type: boolean
      type:
        $ref: '#/definitions/FieldDescriptorType'
        description: The type of field descriptor.
        enum:
          - RADIO_GROUP
          - SELECT
          - FILTERABLE_SELECT
          - CHECK_BOX
          - TEXT_AREA
          - TEXT
          - UPLOAD_FILE
          - HASHED_TEXT
  CheckBoxFieldDescriptor:
    allOf:
      - description: >-
          A boolean field typically rendered as a checkbox in a configuration
          UI.
        properties:
          advanced:
            description: Whether this is an advanced field or not.
            type: boolean
          defaultValue:
            description: Default value of the field.
            type: string
          description:
            description: Description of the field.
            type: string
          label:
            description: Label of the field to be displayed in the administrative console.
            type: string
          name:
            description: Name of the field.
            type: string
          required:
            description: Whether a value is required for this field or not.
            type: boolean
          type:
            $ref: '#/definitions/FieldDescriptorType'
            description: The type of field descriptor.
            enum:
              - RADIO_GROUP
              - SELECT
              - FILTERABLE_SELECT
              - CHECK_BOX
              - TEXT_AREA
              - TEXT
              - UPLOAD_FILE
              - HASHED_TEXT
      - $ref: '#/definitions/FieldDescriptor'
  FieldDescriptor:
    description: Describes a plugin configuration field.
    discriminator: type
    properties:
      advanced:
        description: Whether this is an advanced field or not.
        type: boolean
      defaultValue:
        description: Default value of the field.
        type: string
      description:
        description: Description of the field.
        type: string
      label:
        description: Label of the field to be displayed in the administrative console.
        type: string
      name:
        description: Name of the field.
        type: string
      required:
        description: Whether a value is required for this field or not.
        type: boolean
      type:
        $ref: '#/definitions/FieldDescriptorType'
        description: The type of field descriptor.
        enum:
          - RADIO_GROUP
          - SELECT
          - FILTERABLE_SELECT
          - CHECK_BOX
          - TEXT_AREA
          - TEXT
          - UPLOAD_FILE
          - HASHED_TEXT
  HashedTextFieldDescriptor:
    allOf:
      - description: A text field that will contain a secure salted hash.
        properties:
          advanced:
            description: Whether this is an advanced field or not.
            type: boolean
          defaultValue:
            description: Default value of the field.
            type: string
          description:
            description: Description of the field.
            type: string
          label:
            description: Label of the field to be displayed in the administrative console.
            type: string
          name:
            description: Name of the field.
            type: string
          required:
            description: Whether a value is required for this field or not.
            type: boolean
          size:
            description: The size of the text field.
            format: int32
            type: integer
          type:
            $ref: '#/definitions/FieldDescriptorType'
            description: The type of field descriptor.
            enum:
              - RADIO_GROUP
              - SELECT
              - FILTERABLE_SELECT
              - CHECK_BOX
              - TEXT_AREA
              - TEXT
              - UPLOAD_FILE
              - HASHED_TEXT
      - $ref: '#/definitions/FieldDescriptor'
  OptionValue:
    description: An option name and value associated with a selection field.
    properties:
      name:
        description: The name of the option.
        type: string
      value:
        description: The value associated with this option.
        type: string
  Pattern:
    properties:
      flags:
        format: int32
        type: integer
      pattern:
        type: string
  PluginConfigDescriptor:
    description: Defines the configuration fields available for a plugin.
    properties:
      actionDescriptors:
        description: The available actions for this plugin.
        items:
          $ref: '#/definitions/ActionDescriptor'
        type: array
      description:
        description: The description of this plugin.
        type: string
      fields:
        description: The configuration fields available for this plugin.
        items:
          $ref: '#/definitions/FieldDescriptor'
        type: array
      tables:
        description: Configuration tables available for this plugin.
        items:
          $ref: '#/definitions/TableDescriptor'
        type: array
  RadioGroupFieldDescriptor:
    allOf:
      - description: >-
          A selection-type field intended to be rendered as a group of radio
          buttons in a UI.
        properties:
          advanced:
            description: Whether this is an advanced field or not.
            type: boolean
          defaultValue:
            description: Default value of the field.
            type: string
          description:
            description: Description of the field.
            type: string
          label:
            description: Label of the field to be displayed in the administrative console.
            type: string
          name:
            description: Name of the field.
            type: string
          optionValues:
            description: The list of option values for this selection field.
            items:
              $ref: '#/definitions/OptionValue'
            type: array
          required:
            description: Whether a value is required for this field or not.
            type: boolean
          type:
            $ref: '#/definitions/FieldDescriptorType'
            description: The type of field descriptor.
            enum:
              - RADIO_GROUP
              - SELECT
              - FILTERABLE_SELECT
              - CHECK_BOX
              - TEXT_AREA
              - TEXT
              - UPLOAD_FILE
              - HASHED_TEXT
      - $ref: '#/definitions/BaseSelectionFieldDescriptor'
      - $ref: '#/definitions/FieldDescriptor'
  SaasPluginDescriptor:
    description: A SaaS Plugin.
    properties:
      configDescriptor:
        $ref: '#/definitions/PluginConfigDescriptor'
        description: >-
          The plugin configuration that includes information to access the
          target service provider.
      description:
        description: The SaaS plugin description.
        type: string
      id:
        description: The SaaS plugin type.
        type: string
      saasPluginFieldInfoDescriptors:
        description: >-
          The SaaS plugin attribute list for mapping from the local data store
          into Fields specified by the service provide.
        items:
          $ref: '#/definitions/SaasPluginFieldInfoDescriptor'
        type: array
  SaasPluginDescriptors:
    description: A collection of SaaS plugins.
    properties:
      items:
        description: The actual list of SaaS plugins.
        items:
          $ref: '#/definitions/SaasPluginDescriptor'
        type: array
  SaasPluginFieldInfoDescriptor:
    description: A Saas Plugin Field configuration.
    properties:
      attributeGroup:
        description: >-
          Indicates whether this field belongs to group of attribute such as
          multivalued or sub-type custom attributes.
        type: boolean
      code:
        description: The name or code that represents a field.
        type: string
      defaultValue:
        description: Default value for the field.
        type: string
      dsLdapMap:
        description: Indicates whether the field can be mapped raw to an LDAP attribute.
        type: boolean
      label:
        description: The label for a field.
        type: string
      maxLength:
        description: Maximum character length for a value.
        format: int32
        type: integer
      minLength:
        description: Minimum character length for a value.
        format: int32
        type: integer
      multiValue:
        description: Whether the field can have multiple values.
        type: boolean
      notes:
        description: Description or notes for the field.
        items:
          type: string
        type: array
      options:
        description: List of Option values available for this field.
        items:
          $ref: '#/definitions/SaasPluginFieldOption'
        type: array
      pattern:
        $ref: '#/definitions/Pattern'
        description: Pattern used to validate values of this field.
      persistForMembership:
        description: The code that represents the field.
        type: boolean
      required:
        description: Indicates whether a value is required for this field.
        type: boolean
      unique:
        description: indicates whether the value of this field is unique.
        type: boolean
    required:
      - code
      - label
  SaasPluginFieldOption:
    description: A plugin configuration field value.
    properties:
      code:
        description: The code that represents the field.
        type: string
      label:
        description: The label for the field.
        type: string
    required:
      - code
      - label
  SelectFieldDescriptor:
    allOf:
      - description: >-
          A selection field that is intended to be rendered as a dropdown list
          of options.
        properties:
          advanced:
            description: Whether this is an advanced field or not.
            type: boolean
          defaultValue:
            description: Default value of the field.
            type: string
          description:
            description: Description of the field.
            type: string
          label:
            description: Label of the field to be displayed in the administrative console.
            type: string
          name:
            description: Name of the field.
            type: string
          optionValues:
            description: The list of option values for this selection field.
            items:
              $ref: '#/definitions/OptionValue'
            type: array
          required:
            description: Whether a value is required for this field or not.
            type: boolean
          type:
            $ref: '#/definitions/FieldDescriptorType'
            description: The type of field descriptor.
            enum:
              - RADIO_GROUP
              - SELECT
              - FILTERABLE_SELECT
              - CHECK_BOX
              - TEXT_AREA
              - TEXT
              - UPLOAD_FILE
              - HASHED_TEXT
      - $ref: '#/definitions/BaseSelectionFieldDescriptor'
      - $ref: '#/definitions/FieldDescriptor'
  TableDescriptor:
    description: Defines a plugin configuration table.
    properties:
      columns:
        description: Get the columns in the table.
        items:
          $ref: '#/definitions/FieldDescriptor'
        type: array
      description:
        description: Description for the table.
        type: string
      label:
        description: Label for the table to be displayed in the administrative console.
        type: string
      name:
        description: The name of the table.
        type: string
      requireDefaultRow:
        description: Configure whether this table requires default row to be set.
        type: boolean
  TextAreaFieldDescriptor:
    allOf:
      - description: A field intended to be rendered as a text box in a UI.
        properties:
          advanced:
            description: Whether this is an advanced field or not.
            type: boolean
          columns:
            description: The number of columns for the text box.
            format: int32
            type: integer
          defaultValue:
            description: Default value of the field.
            type: string
          description:
            description: Description of the field.
            type: string
          label:
            description: Label of the field to be displayed in the administrative console.
            type: string
          name:
            description: Name of the field.
            type: string
          required:
            description: Whether a value is required for this field or not.
            type: boolean
          rows:
            description: The number of rows for the text box.
            format: int32
            type: integer
          type:
            $ref: '#/definitions/FieldDescriptorType'
            description: The type of field descriptor.
            enum:
              - RADIO_GROUP
              - SELECT
              - FILTERABLE_SELECT
              - CHECK_BOX
              - TEXT_AREA
              - TEXT
              - UPLOAD_FILE
              - HASHED_TEXT
      - $ref: '#/definitions/FieldDescriptor'
  TextFieldDescriptor:
    allOf:
      - description: A text field.
        properties:
          advanced:
            description: Whether this is an advanced field or not.
            type: boolean
          defaultValue:
            description: Default value of the field.
            type: string
          description:
            description: Description of the field.
            type: string
          encrypted:
            description: >-
              Determines whether the field value should be masked in the UI and
              encrypted on disk.
            type: boolean
          label:
            description: Label of the field to be displayed in the administrative console.
            type: string
          name:
            description: Name of the field.
            type: string
          required:
            description: Whether a value is required for this field or not.
            type: boolean
          size:
            description: The size of the text field.
            format: int32
            type: integer
          type:
            $ref: '#/definitions/FieldDescriptorType'
            description: The type of field descriptor.
            enum:
              - RADIO_GROUP
              - SELECT
              - FILTERABLE_SELECT
              - CHECK_BOX
              - TEXT_AREA
              - TEXT
              - UPLOAD_FILE
              - HASHED_TEXT
      - $ref: '#/definitions/FieldDescriptor'
  UploadFileFieldDescriptor:
    allOf:
      - description: A field which allows the user to upload a file.
        properties:
          advanced:
            description: Whether this is an advanced field or not.
            type: boolean
          defaultValue:
            description: Default value of the field.
            type: string
          description:
            description: Description of the field.
            type: string
          label:
            description: Label of the field to be displayed in the administrative console.
            type: string
          name:
            description: Name of the field.
            type: string
          required:
            description: Whether a value is required for this field or not.
            type: boolean
          type:
            $ref: '#/definitions/FieldDescriptorType'
            description: The type of field descriptor.
            enum:
              - RADIO_GROUP
              - SELECT
              - FILTERABLE_SELECT
              - CHECK_BOX
              - TEXT_AREA
              - TEXT
              - UPLOAD_FILE
              - HASHED_TEXT
      - $ref: '#/definitions/FieldDescriptor'
host: 'ip-10-101-29-72:9999'
info:
  title: 'ip-10-101-29-72:9999'
  version: v1
paths:
  /idp/connectors/descriptors:
    get:
      consumes:
        - application/json
      operationId: getIdpConnectorDescriptors
      produces:
        - application/json
      responses:
        '200':
          description: Success.
          schema:
            $ref: '#/definitions/SaasPluginDescriptors'
        '403':
          description: >-
            PingFederate does not have its IdP role enabled. Operation not
            available.
      summary: Get the list of available IdP connector descriptors.
  '/idp/connectors/descriptors/{id}':
    get:
      consumes:
        - application/json
      operationId: getIdpConnectorDescriptorById
      parameters:
        - description: the type of connector descriptor to fetch.
          in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Success.
          schema:
            $ref: '#/definitions/SaasPluginDescriptor'
        '403':
          description: >-
            PingFederate does not have its IdP role enabled. Operation not
            available.
      summary: Get the list of available connector descriptors.
schemes:
  - https
swagger: '2.0'

